//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rental_service
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bike brand.
    /// </summary>
    //  *** Start programmer edit section *** (BikeBrand CustomAttributes)

    //  *** End programmer edit section *** (BikeBrand CustomAttributes)
    [AutoAltered()]
    [Caption("Bike brand")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BikeBrandE", new string[] {
            "Name as \'Name\'"})]
    [View("BikeBrandL", new string[] {
            "Name as \'Name\'"})]
    public class BikeBrand : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        //  *** Start programmer edit section *** (BikeBrand CustomMembers)

        //  *** End programmer edit section *** (BikeBrand CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (BikeBrand.Name CustomAttributes)

        //  *** End programmer edit section *** (BikeBrand.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (BikeBrand.Name Get start)

                //  *** End programmer edit section *** (BikeBrand.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (BikeBrand.Name Get end)

                //  *** End programmer edit section *** (BikeBrand.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (BikeBrand.Name Set start)

                //  *** End programmer edit section *** (BikeBrand.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (BikeBrand.Name Set end)

                //  *** End programmer edit section *** (BikeBrand.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BikeBrandE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BikeBrandE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BikeBrandE", typeof(IIS.Rental_service.BikeBrand));
                }
            }
            
            /// <summary>
            /// "BikeBrandL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BikeBrandL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BikeBrandL", typeof(IIS.Rental_service.BikeBrand));
                }
            }
        }
    }
}
