//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rental_service
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Rent point.
    /// </summary>
    //  *** Start programmer edit section *** (RentPoint CustomAttributes)

    //  *** End programmer edit section *** (RentPoint CustomAttributes)
    [AutoAltered()]
    [Caption("Rent point")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RentPointE", new string[] {
            "Address as \'Address\'"})]
    [View("RentPointL", new string[] {
            "Address as \'Address\'"})]
    public class RentPoint : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        //  *** Start programmer edit section *** (RentPoint CustomMembers)

        //  *** End programmer edit section *** (RentPoint CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        //  *** Start programmer edit section *** (RentPoint.Address CustomAttributes)

        //  *** End programmer edit section *** (RentPoint.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                //  *** Start programmer edit section *** (RentPoint.Address Get start)

                //  *** End programmer edit section *** (RentPoint.Address Get start)
                string result = this.fAddress;
                //  *** Start programmer edit section *** (RentPoint.Address Get end)

                //  *** End programmer edit section *** (RentPoint.Address Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (RentPoint.Address Set start)

                //  *** End programmer edit section *** (RentPoint.Address Set start)
                this.fAddress = value;
                //  *** Start programmer edit section *** (RentPoint.Address Set end)

                //  *** End programmer edit section *** (RentPoint.Address Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RentPointE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RentPointE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RentPointE", typeof(IIS.Rental_service.RentPoint));
                }
            }
            
            /// <summary>
            /// "RentPointL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RentPointL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RentPointL", typeof(IIS.Rental_service.RentPoint));
                }
            }
        }
    }
}
